src/peer_connection.c

If `PeerConnection` is not zeroed upon creation checking for its field to NULL is meaningless (as fields contain garbage) and leads to sigsegvs.
For example this happens in `peer_connection_ice_recv_cb`:
```c
if(pc->ontrack != NULL) {
pc->ontrack(buf, len, pc->ontrack_userdata);
}
```
This PR contains hotfix for this problem.

fix crash due to misinitialization of PeerConnection

---

src/ice.c

SDP parsers that split on `\r\n` will get caught on this line, merging the candidate and the following line together. Tested against [werift](https://github.com/shinyoshiaki/werift-webrtc).

ice: fix newlines after candidates

---

src/agent.c
src/mdns.c

`sys/select.h` is needed to define `fd_set`.

build: include missing headers to build with musl libc

---

src/rtcp.h
src/rtp.h

Hello!
Thank you so much for adding ExternalProject_Add's for the third party dependencies in this lib. I was maintaining my own fork for a while which added those, along with this small header variant that fixes compilation for MacOS.

build: Header paths differ on MacOS Sonoma

---

CMakeLists.txt
src/CMakeLists.txt

Building with musl for RISC-V prefers static libpeer.

build: allow configuring static/shared libpeer builds

---

src/agent.h
src/peer_signaling.c

Werift can return SDPs of over 4096 in size and more than 10 candidates. This change makes these buffers configurable at build time.

signaling: configurable buffer sizes via macros

---

src/utils.c

Add <time.h> to utils.c to fix compile error on Linux

Fix missing include for `time`

---

src/rtp.c

Avoid crashing when function is not set in config

Call the on_packet function only if it set, if not set behave normally

---

src/config.h
src/peer_signaling.c
src/peer_signaling.h
src/ssl_transport.c
src/ssl_transport.h

Allows library to be used without MQTT/HTTP dependencies

Add 'DISABLE_PEER_SIGNALING'

---

src/ice.c
src/peer_connection.c
src/peer_connection.h

Implement peer_connection_add_ice_candidate

---

src/agent.c

Pion's STUN implementation rejects this as invalid

Only send STUN USE_CANDIDATE if controlling Agent

---

src/dtls_srtp.c

We are using self-signed certificates. If the remote doesn't generate with "dtls_srtp" as the CA negotation will fail with this set.

Set MBEDTLS_SSL_CERT_REQ_CA_LIST_DISABLED

---

src/agent.c
src/peer_connection.c

This allows add_ice_candidate to work when answering

Don't clear candidates on set_remote_description

---

src/peer_connection.c

Can't depend on audio/video being a mid name

Use media name and not mid to find audio/video

---

examples/esp32/README.md
examples/esp32/main/Kconfig.projbuild
examples/esp32/main/camera.c

Also update README with Freenove board I used

Add CONFIG_ESP32S3_EYE to examples/esp32s3

---

src/peer_signaling.h

if define DISABLE_PEER_SIGNALING, the file will ends with lossing a brackets.

fix compile error for DISABLE_PEER_SIGNALING

---

examples/generic/main.c
src/buffer.c
src/peer_connection.c
src/sctp.c
src/sctp.h
src/stun.c

After turning on the ADDRESS_SANITIZER switch, I noticed that there was some memory leak.
PeerConnection: dtls_srtp and sctp were not released.
sctp_incoming_data_cb did't free the memory that usrsctp allocates
Buffer: itself was not released.

fix memory leak

---

src/peer_signaling.c
src/sctp.c

1. Call usrsctp_finish to release the sctp thread
2. Call ssl_transport_disconnect to release the memory of g_ps.net_ctx

Add memory release and thread release

---

src/sctp.c

Before we only fired on DATA. If we are the creator of the DataChannel the remote isn't going to send us a message. Changing this allows the DataChannel to be created in the callback when SCTP has opened.

Fire SCTP onopen for INIT/INIT_ACK

---

src/dtls_srtp.c

According to RFC5764 section 4.2, keys are assigned as shown below: client_write_SRTP_master_key[SRTPSecurityParams.master_key_len]; server_write_SRTP_master_key[SRTPSecurityParams.master_key_len]; client_write_SRTP_master_salt[SRTPSecurityParams.master_salt_len]; server_write_SRTP_master_salt[SRTPSecurityParams.master_salt_len];
TEST: libpeer works as dtls srtp client

Fixed DTLS SRTP keys for DTLS_SRTP_ROLE_CLIENT

---

src/mdns.c

libpeer现在的mdns解析没有对hostname进行校验。
如果局域网中有其他设备正在响应mdns，libpeer可能会解析出错误的mdns响应结果。

fix mdns parsed incorrent hostname

---

src/sdp.c

According to RFC 4566 section 5:
Media description, if present
m=  (media name and transport address)
i=* (media title)
c=* (connection information -- optional if included at
session level)
b=* (zero or more bandwidth information lines)
k=* (encryption key)
a=* (zero or more media attribute lines)
TEST: can be parsed with jsdp

The c line in the media description should come after the m line.

---

src/stun.c

Hi, author. In LEVEL_DEBUG mode, stun.c uses <%08" PRIu32 "> to print logs, but the <inttypes.h> header is missing. It may be necessary to add <inttypes.h> to stun.c.

In LEVEL_DEBUG mode, stun.c uses <%08" PRIu32 "> to print logs, but the <inttypes.h> header is missing.

---

src/ssl_transport.c

The function "ssl_transport_send()" may need to be modified to include a retry mechanism for handling SSL write operations. The modifications are as follows:
- Prevent infinite loops when write operations repeatedly fail
- Provide better error handling by limiting the number of retries

Add a retry mechanism for handling SSL write operations

---

src/sctp.c

If we fire onopen too early we might be sending data before other SCTP steps are finished. For example, with aiortc, this results in the datachannel connection not being established.
I'm not sure this is correct, but it seems to fix the issue I was having with `aiortc`. That said, it seems to make sense to fire `onopen` after everything is completed.

sctp: fire onopen after COOKIE/COOKIE_ACK is completed

---

src/stun.c

Very very odd issue I found using `libpeer` with idf version 5.4.1.
The stun header has a particular pattern on the first 12 bytes that cause the udp client to not send any data. I am running on an esp32s3 wrroom.
It is causing the ICE negotiation to fail after an offer / answer exchange between two peers.
This was the original stun request i was trying to send. It will fail after 11 bytes being sent.
```
00 01 00 54 21 12 A4 42 12 34 56 78 90 AB CD EF 
12 34 56 78 00 06 00 15 7A 4D 51 54 77 63 56 72 
45 43 42 4A 49 72 68 65 3A 64 52 56 43 00 00 00 
00 24 00 04 FE 4E E5 FD 00 25 00 00 80 2A 00 08 
00 00 00 00 00 00 00 00 00 08 00 14 7F 8F FD 4B 
E4 55 C6 9A E5 8A D2 29 98 6D 62 C8 17 19 23 54 
80 28 00 04 31 9A 96 0E
```
How to recreate:
```
#include <esp_log.h>
#include <nvs_flash.h> …
```

fix: bad udp payload on esp32

---

src/config.h
src/peer.c
src/peer_connection.c
src/sctp.c

- Always return on `srtp_init`/`calloc` failure
- Don't overwrite `LOG_REDIRECT` if it is already set
- Handle incoming binary messages if usrsctp is not enabled

Minor bugfixes
